"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, CheckCircle2, Link2, Users, Wallet, Search, ChevronRight } from "lucide-react";
import type { SubmissionData,Participant } from "@/lib/campaign/submissions";
import { currentSubmissions,usableApproval } from "@/lib/campaign/submissions";
import type { BudgetData,BudgetFee } from "@/lib/campaign/budget";
import { operationFor,operationState,operationLabels,operationsSummary,termsFor,engagementLabels,type Operation,type OperationsRow,type OperationsPolicy,type FeeTerms } from "@/lib/campaign/operations";
import { saveCampaignOperations } from "@/app/actions/campaign-operations";
import { saveBudgetAction } from "@/app/actions/campaign-budget";
import { ParticipantSheet,SubmissionsPanel } from "./SubmissionsPanel";
import { ManualParticipantEditor } from "./ManualParticipantEditor";
import { buttonClass,inputClass,ErrorText,useAction,Editor } from "./Controls";
const won=(n:number|null|undefined)=>n==null?"미확인":Number(n).toLocaleString("ko-KR")+"원";
const deadlineLabel=(v:string)=>{const iso=new Date(Date.parse(v)+9*3600000).toISOString();return Number(iso.slice(5,7))+"/"+Number(iso.slice(8,10))+" "+iso.slice(11,16);};
const short=(v:string|null)=>v?Number(v.slice(5,7))+"/"+Number(v.slice(8,10)):"일정 미정";
const colors:Record<string,string>={approved:"bg-emerald-50 text-emerald-800",scheduled:"bg-indigo-50 text-indigo-800",link_needed:"bg-amber-50 text-amber-900",changes_requested:"bg-rose-50 text-rose-800",cancelled:"bg-muted text-ink-3",on_hold:"bg-muted text-ink-3"};
const field=inputClass+" w-full";
type Props={data:SubmissionData;budget:BudgetData;operations:OperationsRow[];policy:OperationsPolicy;boards:{id:string;title:string|null}[];initialView?:string};
export function OperationsPanel({data,budget,operations,policy,boards,initialView}:Props){
 const router=useRouter(),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[owner,setOwner]=useState("all"),[view,setView]=useState(initialView==="budget"?"budget":"list"),[selected,setSelected]=useState<string|null>(null),[legacy,setLegacy]=useState(false);
 const all=data.participants.map(p=>({p,o:operationFor(p,operations),f:budget.fees.find(f=>f.participant_id===p.id)}));
 const active=all.filter(x=>x.p.active&&!["on_hold","cancelled"].includes(x.o.engagement));
 const summary=operationsSummary(budget,operations,data);
 const rank:Record<string,number>={link_needed:0,changes_requested:1,review:2,scheduled:3,unscheduled:4,negotiating:5,approved:6,on_hold:7,cancelled:8};
 const items=all.filter(({p,o,f})=>{
   const state=operationState(p,o,data);
   if(filter==="inactive"?!["cancelled","on_hold"].includes(state):["cancelled","on_hold"].includes(state))return false;
   if(filter==="money"&&f?.amount!=null)return false;
   if(!["all","inactive","money"].includes(filter)&&state!==filter)return false;
   if(owner!=="all"&&o.owner_label!==owner)return false;
   return (p.display_name+" "+p.ig_handle+" "+o.accounts.map(a=>a.handle).join(" ")+" "+o.owner_label).toLowerCase().includes(query.toLowerCase());
 }).sort((a,b)=>view==="calendar"?(a.o.planned_on??"9999").localeCompare(b.o.planned_on??"9999")||a.p.display_name.localeCompare(b.p.display_name,"ko"):rank[operationState(a.p,a.o,data)]-rank[operationState(b.p,b.o,data)]||(a.o.planned_on??"9999").localeCompare(b.o.planned_on??"9999")||a.p.display_name.localeCompare(b.p.display_name,"ko"));
 const count=(state:string)=>active.filter(x=>operationState(x.p,x.o,data)===state).length;
 const cards=[["all","운영 대상",active.length,Users],["scheduled","참여 예정",count("scheduled"),CalendarDays],["approved","승인 완료",count("approved"),CheckCircle2],["link_needed","링크 확인",count("link_needed"),Link2],["money","금액 미확인",summary.unpriced,Wallet]] as const;
 const person=data.participants.find(p=>p.id===selected);
 const reload=async()=>{router.refresh();};
 return <section className="space-y-5" aria-label="통합 캠페인 운영">
 <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">캠페인 운영</h2><p className="mt-1 text-xs text-ink-3">공통 제출 마감 {data.settings.deadline?deadlineLabel(data.settings.deadline):"미정"} KST · 고유 게시물 {summary.uniquePosts}개</p></div><ManualParticipantEditor project={data.settings.project_id} onSaved={reload}/></div>
 <div className="grid grid-cols-2 gap-2 lg:grid-cols-5">{cards.map(([key,label,n,Icon])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)} className={`rounded-xl border p-4 text-left transition-colors ${filter===key?"border-emerald-700 bg-emerald-50 text-emerald-950":"border-border bg-card"}`}><span className="flex items-center justify-between text-xs"><span>{label}</span><Icon size={15}/></span><strong className="mt-2 block text-2xl tabular-nums">{n}<span className="ml-1 text-sm font-normal">명</span></strong></button>)}</div>
 {budget.canViewFinance&&<div className="rounded-xl border border-emerald-200 bg-emerald-50/70 p-4 text-emerald-950"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-xs">집행 목표 / 상한</span><p className="font-semibold">{won(policy.data.spend_target)} / {won(policy.data.spend_cap)}</p></div><div><span className="text-xs">필요 예상액 · 확인분</span><p className="font-semibold">{won(summary.knownRequired)}</p></div><div><span className="text-xs">상한까지 · 확인분 차감</span><p className="font-semibold">{policy.data.spend_cap==null?"미설정":won(policy.data.spend_cap-summary.knownRequired)}</p></div><PolicyEditor project={data.settings.project_id} policy={policy}/></div><p className="mt-3 text-xs leading-relaxed">합의 기본금 {won(summary.agreed)} · 협의 예상 {won(summary.estimate)} · 성과 조건 {won(summary.conditional)} · 협의 중 예약 {won(summary.offered)}<br/>금액 미확인 {summary.unpriced}명 · 운영비 {won(summary.operations)} · 클라이언트 예산 {won(budget.settings.total_amount)}<br/>확인된 금액만 합산한 수치이며, 지급 완료액은 아닙니다.</p></div>}
 {(policy.data.notes||policy.data.retention_note||policy.data.payout_note)&&<details className="rounded-xl border border-border bg-card px-4 py-3"><summary className="cursor-pointer text-sm font-medium">운영 기준 · 확인할 사항</summary><div className="mt-3 space-y-3 whitespace-pre-line text-sm text-ink-3"><p>{policy.data.retention_note}</p><p>정산: {policy.data.payout_note||"미정"}</p><p>{policy.data.notes}</p></div></details>}
 <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-1 rounded-lg bg-secondary p-1">{[["list","운영 명단"],["calendar","일정순"],["budget","금액 비교"]].map(([k,l])=><button key={k} aria-pressed={view===k} className={`rounded-md px-3 py-2 text-sm ${view===k?"bg-card font-semibold shadow-sm":"text-ink-3"}`} onClick={()=>setView(k)}>{l}</button>)}</div><div className="flex min-w-0 flex-wrap gap-2"><label className="flex items-center gap-2 rounded-lg border border-border bg-card px-3"><Search size={15}/><input aria-label="운영 참여자 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="이름 · 계정 · 담당자" className="min-w-0 bg-transparent py-2 text-sm outline-none"/></label><select aria-label="담당자 필터" className={inputClass} value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">담당자 전체</option><option value="">미지정</option>{[...new Set(all.map(x=>x.o.owner_label).filter(Boolean))].sort().map(n=><option key={n}>{n}</option>)}</select></div></div>
 <div className="flex flex-wrap gap-2">{[["all","전체"],["unscheduled","일정 확인"],["review","제출 검토"],["changes_requested","수정 요청"],["negotiating","협의 중"],["inactive","보류·취소"]].map(([k,l])=><button key={k} className={`rounded-full border px-3 py-1 text-xs ${filter===k?"border-primary bg-primary text-primary-foreground":"border-border"}`} onClick={()=>setFilter(k)}>{l}</button>)}<span className="ml-auto text-xs text-ink-3">{items.length}명</span></div>
 <div className="overflow-hidden rounded-xl border border-border bg-card"><div className={`hidden gap-4 bg-secondary/60 px-4 py-3 text-xs text-ink-3 lg:grid ${view==="budget"?"grid-cols-[1.4fr_1fr_1fr_1fr_1.2fr]":"grid-cols-[1.4fr_1fr_1fr_1.2fr_1fr]"}`}>{(view==="budget"?["참여자 · 담당","산출가 / 상대 요구","제안 / 기본금","성과 조건","상태 · 상세"]:["참여자","예정 · 진행","업로드","출연료 · 조건","담당 · 다음 할 일"]).map(x=><span key={x}>{x}</span>)}</div>
 {items.map(({p,o,f})=>{
 const state=operationState(p,o,data),terms=termsFor(f),subs=currentSubmissions(data,p.id),expected=Math.max(1,o.accounts.reduce((s,a)=>s+a.count,0));
 const approved=new Set(subs.filter(s=>usableApproval(s,data)).map(s=>s.post_id)).size;
 const next=o.next_action||(state==="link_needed"?"실제 링크 받기":state==="unscheduled"?"일정 확인":state==="review"?"제출 검토":f?.amount==null?"출연료 확인":terms.bonus_amount?"성과 확인":"상세 보기");
 return <article key={p.id} className={`grid grid-cols-2 items-start gap-3 border-t border-border/70 px-4 py-4 text-sm lg:items-center lg:gap-4 ${view==="budget"?"lg:grid-cols-[1.4fr_1fr_1fr_1fr_1.2fr]":"lg:grid-cols-[1.4fr_1fr_1fr_1.2fr_1fr]"}`}>
 <div className="col-span-2 min-w-0 lg:col-span-1"><button onClick={()=>setSelected(p.id)} className="flex items-center gap-1 text-left font-semibold hover:underline">{p.display_name}<ChevronRight size={13}/></button><p className="mt-1 break-all text-xs text-ink-3">{o.accounts.length?o.accounts.map(a=>"@"+a.handle).join(" · "):p.ig_handle?"@"+p.ig_handle:"계정 확인 필요"}</p>{view==="budget"&&<p className="mt-1 text-xs text-ink-3">{o.owner_label||"담당 미지정"}</p>}</div>
 {view==="budget"?<><div><span className="text-xs text-ink-3 lg:hidden">산출가 / 상대 요구<br/></span>{won(terms.guide_amount)}<p className="mt-1 text-xs text-ink-3">요구 {won(terms.quote_amount)}</p></div><div><span className="text-xs text-ink-3 lg:hidden">제안 / 기본금<br/></span>{won(terms.offer_amount)}<p className="mt-1 text-xs text-ink-3">기본 {won(terms.base_amount)}</p></div><div>{terms.bonus_amount?<>{Number(terms.threshold).toLocaleString()}회 → {won(terms.bonus_amount)}<p className="mt-1 text-xs text-ink-3">{terms.condition_state==="met"?"달성 확인":terms.condition_state==="below"?"기준 미달":"달성 미확인"}</p></>:"조건 없음"}</div><button onClick={()=>setSelected(p.id)} className="text-left text-xs"><span className="rounded bg-secondary px-2 py-1">{f?.amount==null?"금액 미확인":f.status==="agreed"?"기본금 합의":"협의 예상"}</span><p className="mt-2">{next} →</p></button></>:<><div><span className={`inline-block rounded px-2 py-1 text-xs ${colors[state]??"bg-secondary text-ink-3"}`}>{state==="scheduled"?short(o.planned_on)+(o.schedule_kind==="upload"?" 업로드":" 참여"):operationLabels[state]}</span>{o.planned_on&&state!=="scheduled"&&<p className="mt-1 text-xs text-ink-3">{short(o.planned_on)} {o.schedule_kind==="upload"?"업로드 예정":"참여 예정"}</p>}</div><div>{subs.length?<><a href={data.posts.find(x=>x.id===subs[0].post_id)?.post_url} target="_blank" rel="noopener noreferrer" className="text-emerald-700 underline underline-offset-4">릴스 열기 ↗</a><p className="mt-1 text-xs text-ink-3">승인 {approved}/{expected}개 {subs.length>1?"· 링크 "+subs.length+"개":""}</p></>:<button onClick={()=>setSelected(p.id)} className={`text-xs ${state==="link_needed"?"text-amber-800":"text-ink-3"}`}>{state==="link_needed"?"실제 링크 필요 →":"링크 등록 +"}</button>}</div><div>{terms.bonus_amount?<>{Number(terms.threshold).toLocaleString()}회 달성 시 {won(terms.bonus_amount)}{terms.base_amount?<> + 기본 {won(terms.base_amount)}</>:null}</>:won(f?.amount)}<p className="mt-1 text-xs text-ink-3">{terms.bonus_amount?(terms.condition_state==="met"?"달성 확인 · 정산 별도":"조건부 · 달성 미확인"):f?.amount==null?"금액 입력 필요":f.status==="agreed"?"합의 완료":"협의 예상"}</p></div><button onClick={()=>setSelected(p.id)} className="text-left text-xs text-ink-2">{next} →<p className="mt-1 text-ink-3">{o.owner_label||"담당 미지정"}</p></button></>}
 </article>})}
 {!items.length&&<p className="p-10 text-center text-sm text-ink-3">해당하는 참여자가 없습니다.</p>}</div>
 {budget.canViewFinance&&<div className="flex flex-wrap items-center gap-3"><FinanceSettings data={budget}/><a className={buttonClass} href={`/projects/${data.settings.project_id}/settlements`}>정산·지급 현황 ↗</a></div>}
 <button className="text-xs text-ink-3 underline" onClick={()=>setLegacy(!legacy)}>{legacy?"기존 관리 닫기":"명단 동기화 · 제출/공개 설정"}</button>
 {legacy&&<SubmissionsPanel initial={data} boards={boards}/>}
 {person&&<ParticipantSheet person={person} data={data} onClose={()=>setSelected(null)} onSaved={reload} extra={<OperationEditor key={person.id+"-"+person.version+"-"+(operations.find(o=>o.participant_id===person.id)?.version??0)} project={data.settings.project_id} person={person} row={operations.find(o=>o.participant_id===person.id)} fee={budget.fees.find(f=>f.participant_id===person.id)}/>}/>}
 </section>;
}
function FinanceSettings({data}:{data:BudgetData}){
 const action=useAction(),[open,setOpen]=useState(false);
 return <Editor title="클라이언트 예산 · 운영비" open={open} onOpenChange={setOpen}><form key={data.settings.version} className="space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),money=(k:string)=>f.get(k)===""?null:Number(f.get(k));action.run(()=>saveBudgetAction(data.settings.project_id,"configure",{version:data.settings.version,total_amount:money("total"),operations_reserve:money("operations"),basis:f.get("basis")}),()=>setOpen(false));}}>
 <label className="block text-sm">클라이언트 예산 (원)<input name="total" type="number" min="0" max="1000000000000" defaultValue={data.settings.total_amount??""} className={field}/></label>
 <label className="block text-sm">운영비·예비비 확보액 (원)<input name="operations" type="number" min="0" max="1000000000000" defaultValue={data.settings.operations_reserve??""} className={field}/></label>
 <label className="block text-sm">금액 기준·확인 근거<textarea name="basis" required maxLength={2000} defaultValue={data.settings.basis} className={field}/></label>
 <p className="text-xs text-ink-3">미확인 금액은 비워 두고, 비용이 없다고 확인된 경우에만 0원을 입력합니다.</p>
 <ErrorText error={action.error}/><button disabled={action.pending} className={buttonClass}>예산·운영비 저장</button></form></Editor>;
}
function Amount({label,value,onChange}:{label:string;value:number|null;onChange:(value:number|null)=>void}){return <label className="block text-xs text-ink-3">{label}<input className={field+" mt-1"} type="number" min="0" max="1000000000000" step="1" value={value??""} onChange={e=>onChange(e.target.value===""?null:Number(e.target.value))}/></label>;}
function OperationEditor({project,person,row,fee}:{project:string;person:Participant;row?:OperationsRow;fee?:BudgetFee}){
 const [ops,setOps]=useState(operationFor(person,row?[row]:[])),[terms,setTerms]=useState(termsFor(fee)),[status,setStatus]=useState(fee?.status??"estimate"),[note,setNote]=useState(fee?.note??""),[moneyDirty,setMoneyDirty]=useState(false),[message,setMessage]=useState("");
 const action=useAction();const term=(key:keyof FeeTerms,value:FeeTerms[keyof FeeTerms])=>{setTerms({...terms,[key]:value});setMoneyDirty(true);};
 return <form className="my-5 space-y-4 rounded-xl border border-border bg-secondary/30 p-4" onSubmit={e=>{e.preventDefault();setMessage("");action.run(()=>saveCampaignOperations(project,"participant",{participant_id:person.id,participant_version:person.version,version:row?.version??0,fields:ops,fee:moneyDirty?{version:fee?.version??0,status,note,terms}:null}),()=>setMessage("운영 정보를 저장했습니다."));}}>
 <h3 className="font-semibold">일정 · 담당 · 비용</h3><div className="grid grid-cols-2 gap-3">
 <label className="text-xs text-ink-3">섭외 상태<select className={field+" mt-1"} value={ops.engagement} onChange={e=>setOps({...ops,engagement:e.target.value as Operation["engagement"]})}>{Object.entries(engagementLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
 <label className="text-xs text-ink-3">담당자<input className={field+" mt-1"} value={ops.owner_label} maxLength={100} onChange={e=>setOps({...ops,owner_label:e.target.value})}/></label>
 <label className="text-xs text-ink-3">예정일<input type="date" className={field+" mt-1"} value={ops.planned_on??""} onChange={e=>setOps({...ops,planned_on:e.target.value||null})}/></label>
 <label className="text-xs text-ink-3">일정 종류<select className={field+" mt-1"} value={ops.schedule_kind} onChange={e=>setOps({...ops,schedule_kind:e.target.value as Operation["schedule_kind"]})}><option value="participation">참여 예정</option><option value="upload">업로드 예정</option></select></label></div>
 <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={ops.upload_reported} onChange={e=>setOps({...ops,upload_reported:e.target.checked})}/>업로드했다고 전달받음</label>
 <label className="block text-xs text-ink-3">다음 할 일<input className={field+" mt-1"} maxLength={300} value={ops.next_action} onChange={e=>setOps({...ops,next_action:e.target.value})}/></label>
 <details className="rounded-lg border border-border bg-card p-3"><summary className="cursor-pointer text-sm">계정별 제작 약속 · {ops.accounts.reduce((n,a)=>n+a.count,0)||1}개</summary><p className="my-2 text-xs text-ink-3">서로 다른 계정은 별도 영상을 약속할 수 있습니다.<br/>공동작업자 게시물은 같은 링크이면 1개로 집계합니다.<br/>계정별 합의금은 아래 기본금의 배분 내역이며 추가 합산하지 않습니다.</p>{ops.accounts.map((a,i)=><div key={i} className="my-3 space-y-2 border-t border-border pt-3"><div className="flex gap-2"><input aria-label={"제작 계정 "+(i+1)} className={field} value={a.handle} placeholder="instagram_handle" onChange={e=>setOps({...ops,accounts:ops.accounts.map((x,j)=>i===j?{...x,handle:e.target.value.toLowerCase().replace(/^@/,"")}:x)})}/><input aria-label={"제작 개수 "+(i+1)} className={inputClass+" w-20"} type="number" min="1" max="10" value={a.count} onChange={e=>setOps({...ops,accounts:ops.accounts.map((x,j)=>i===j?{...x,count:Number(e.target.value)}:x)})}/><button type="button" aria-label={"계정 약속 제거 "+(i+1)} onClick={()=>setOps({...ops,accounts:ops.accounts.filter((_,j)=>i!==j)})}>×</button></div><div className="grid grid-cols-2 gap-2"><Amount label="계정 산출가" value={a.guide_amount} onChange={v=>setOps({...ops,accounts:ops.accounts.map((x,j)=>i===j?{...x,guide_amount:v}:x)})}/><Amount label="계정 합의금 · 기본금 배분" value={a.agreed_amount} onChange={v=>setOps({...ops,accounts:ops.accounts.map((x,j)=>i===j?{...x,agreed_amount:v}:x)})}/></div></div>)}<button type="button" disabled={ops.accounts.length>=10} className={buttonClass} onClick={()=>setOps({...ops,accounts:[...ops.accounts,{handle:"",count:1,guide_amount:null,agreed_amount:null}]})}>계정 약속 추가</button></details>
 <details className="rounded-lg border border-border bg-card p-3"><summary className="cursor-pointer text-sm">금액 협의 · {won(fee?.amount)}</summary><div className="mt-3 grid grid-cols-2 gap-3">{([["guide_amount","deetz 산출가"],["quote_amount","상대 요구가"],["offer_amount","우리 제안가"],["base_amount","기본금 · 총액"],["bonus_amount","성과 추가금 · 총액"],["threshold","성과 기준 · 조회/재생 횟수"]] as const).map(([k,l])=><Amount key={k} label={l} value={terms[k]} onChange={v=>term(k,v)}/>)}</div>
 <label className="my-3 block text-xs text-ink-3">기본금 합의 상태<select className={field+" mt-1"} value={status} onChange={e=>{setStatus(e.target.value as "estimate"|"agreed");setMoneyDirty(true);}}><option value="estimate">협의 예상</option><option value="agreed">합의 완료</option></select></label>
 <label className="my-3 block text-xs text-ink-3">성과 확인<select className={field+" mt-1"} value={terms.condition_state} onChange={e=>term("condition_state",e.target.value)}><option value="unmeasured">미측정·달성 미확인</option><option value="below">기준 미달</option><option value="met">달성 확인</option></select></label>
 <label className="my-3 block text-xs text-ink-3">성과 기준·확인 근거<textarea className={field+" mt-1"} maxLength={2000} value={terms.condition_note} onChange={e=>term("condition_note",e.target.value)}/></label>
 <label className="my-3 block text-xs text-ink-3">금액 변경 근거<textarea className={field+" mt-1"} value={note} maxLength={2000} required={moneyDirty} onChange={e=>{setNote(e.target.value);setMoneyDirty(true);}}/></label><p className="text-xs text-ink-3">예상액은 기본금 + 성과 추가금입니다.<br/>제안가·산출가·계정별 배분은 추가 합산하지 않습니다.</p></details>
 <label className="block text-xs text-ink-3">운영 메모<textarea className={field+" mt-1"} rows={4} value={ops.note} maxLength={6000} onChange={e=>setOps({...ops,note:e.target.value})}/></label>
 {person.note&&<details className="text-xs text-ink-3"><summary>기존 등록 근거</summary><p className="mt-2 whitespace-pre-line">{person.note}</p></details>}
 <ErrorText error={action.error}/><p role="status" className="text-sm">{message}</p><button disabled={action.pending} className={buttonClass}>{action.pending?"저장 중…":"운영 정보 저장"}</button>
 </form>;
}
function PolicyEditor({project,policy}:{project:string;policy:OperationsPolicy}){
 const action=useAction();const [open,setOpen]=useState(false);
 return <Editor title="집행 기준" open={open} onOpenChange={setOpen}><form key={policy.version} className="space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),money=(key:string)=>f.get(key)===""?null:Number(f.get(key));action.run(()=>saveCampaignOperations(project,"settings",{version:policy.version,fields:{spend_target:money("target"),spend_cap:money("cap"),notes:f.get("notes"),payout_note:f.get("payout"),retention_note:f.get("retention")}}),()=>setOpen(false));}}>
 <label className="block text-sm">집행 목표 (원)<input name="target" type="number" min="0" max="1000000000000" defaultValue={policy.data.spend_target??""} className={field}/></label><label className="block text-sm">집행 상한 (원)<input name="cap" type="number" min="0" max="1000000000000" defaultValue={policy.data.spend_cap??""} className={field}/></label>
 <label className="block text-sm">운영 기준·확인 사항<textarea name="notes" maxLength={12000} rows={7} defaultValue={policy.data.notes??""} className={field}/></label><label className="block text-sm">업로드 유지 기준<textarea name="retention" maxLength={1000} defaultValue={policy.data.retention_note??""} className={field}/></label><label className="block text-sm">정산 일정<textarea name="payout" maxLength={1000} defaultValue={policy.data.payout_note??""} className={field}/></label>
 <ErrorText error={action.error}/><button className={buttonClass} disabled={action.pending}>집행 기준 저장</button></form></Editor>;
}
