// Auto-generated by `npm run db:types`. Do not edit by hand.
// First run: requires `supabase login` once on this machine.
// Until then, this is a permissive placeholder so the build passes.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any;
