export type VisaDocumentLanguage = "ko" | "en" | "ja";

export const VISA_DOCUMENT_LANGUAGES: Array<{ value: VisaDocumentLanguage; label: string }> = [
  { value: "ko", label: "한국어" },
  { value: "en", label: "English" },
  { value: "ja", label: "日本語" },
];

export const VISA_DOCUMENT_COPY = {
  en: {
    languageLabel: "Language",
    backToVisa: "Visa & Korea",
    secureIntake: "Secure document intake",
    title: "Visa document information",
    intro: "Enter the information needed to prepare your Korean visa documents. Your draft is saved quietly while you work, and passport and national identification numbers are encrypted before storage.",
    steps: ["Personal details", "Nationality & passport", "Emergency contact", "Education", "Family", "Korea visits", "Other travel", "Attachments & submit"],
    stepProgress: (current: number, total: number, title: string) => `Step ${current} of ${total} · ${title}`,
    saving: "Saving…",
    saved: "Saved",
    submitted: "Submitted",
    reloadRequired: "Reload required",
    saveFailed: "Save failed",
    changesPending: "Changes pending",
    submitAfterSaving: "Please submit again after the draft has finished saving.",
    submitSuccess: "Your information has been submitted. Our team will contact you if anything else is needed.",
    validationError: "Please complete the required fields and confirmations before submitting.",
    conflictError: "This draft was changed in another tab. Reload the page before continuing.",
    acceptedError: "Documents already accepted by the team cannot be edited.",
    paidOnlyError: "Only your own paid program case can be submitted.",
    secureStorageError: "Secure storage is temporarily unavailable. Please try again shortly.",
    draftSaveError: "The draft could not be saved. Your entries remain in this tab.",
    attachmentIncomplete: "Upload one passport copy, one dancer profile, one ID photo, and at least four activity photos before submitting.",
    attachmentUploadFailed: "The file could not be uploaded. Please try again.",
    attachmentDeleteFailed: "The file could not be removed. Please try again.",
    attachmentSlotConflict: "That activity-photo slot was filled in another tab. Reload the page and try again.",
    attachmentAcceptedError: "Files already accepted by the team cannot be changed.",
    fullNameEnglish: "Full name in English",
    hanjaName: "Name in Chinese characters (Hanja)",
    hanjaHint: "Optional in the database, but required for applicants from countries that normally use Chinese characters, including Japan and China.",
    email: "Email",
    birthDate: "Date of birth",
    mobilePhone: "Mobile phone",
    homeTelephone: "Home telephone",
    noHomeTelephone: "I do not have a home telephone.",
    homeCountryAddress: "Address in home country",
    currentResidenceDifferent: "My current residential address is different from my home-country address.",
    currentResidenceAddress: "Current residential address",
    koreaPlannedAddress: "Planned address in Korea",
    nationalId: "National identification number",
    nationalIdHint: "Use the resident or national identification number issued by your home country. Do not enter a Korean resident registration number.",
    japanNationalIdHint: "Japanese My Number is not collected on this page.",
    nationalIdNotApplicable: "Not issued / not applicable.",
    primaryNationality: "Primary nationality",
    dualNationalityQuestion: "Do you have multiple nationalities?",
    yes: "Yes",
    no: "No",
    otherNationalityCountries: "Other nationality countries",
    countriesCommaHint: "Separate multiple countries with commas.",
    primaryPassportType: "Primary passport type",
    passportNumber: "Primary passport number",
    passportIssuingCountry: "Issuing country",
    passportExpiryDate: "Expiry date",
    passportTypes: [
      { value: "ordinary", label: "Ordinary" },
      { value: "diplomatic", label: "Diplomatic" },
      { value: "official", label: "Official" },
      { value: "other", label: "Other" },
    ],
    hasOtherPassport: "I have another valid passport.",
    otherPassportType: "Passport type",
    otherPassportNumber: "Passport number",
    removePassport: "Remove passport",
    addPassport: "Add passport",
    usedOtherName: "I previously entered or departed Korea under a different name.",
    previousNamePlaceholder: "Previous full name in English",
    previousNameAria: "Previous English name",
    removeNameAria: "Remove name",
    addPreviousName: "Add previous name",
    emergencyIntro: "This person must be reachable while you are staying in Korea.",
    nameEnglish: "Name in English",
    phoneNumber: "Phone number",
    countryOfResidence: "Country of residence",
    countryExample: "e.g. Korea, Japan",
    relationship: "Relationship",
    relationshipExample: "e.g. family, friend, company",
    highestEducation: "Highest education",
    select: "Select",
    educationLevels: [
      { value: "high_school", label: "High school graduate" },
      { value: "bachelor", label: "Bachelor's degree" },
      { value: "master", label: "Master's degree" },
      { value: "doctorate", label: "Doctorate" },
    ],
    schoolName: "School name",
    city: "City",
    region: "State / prefecture / province",
    country: "Country",
    maritalStatus: "Marital status",
    maritalStatuses: [
      { value: "single", label: "Single" },
      { value: "married", label: "Married" },
      { value: "divorced", label: "Divorced" },
    ],
    spouseName: "Spouse full name in English",
    spouseBirthDate: "Spouse date of birth",
    spouseNationality: "Spouse nationality",
    spouseResidence: "Spouse residence",
    spousePhone: "Spouse phone",
    hasChildren: "I have children.",
    childrenCount: "Number of children",
    hasFamilyInKorea: "I currently have family in Korea.",
    familyNamePlaceholder: "Full name in English",
    familyNameAria: "Family name",
    familyBirthDateAria: "Family birth date",
    familyNationality: "Nationality",
    familyNationalityAria: "Family nationality",
    familyRelationship: "Relationship",
    familyRelationshipAria: "Family relationship",
    remove: "Remove",
    addFamilyMember: "Add family member",
    accompanyingFamilyQuestion: "Family will accompany me on this entry.",
    familyDefinition: "Family means spouse, children, parents, or siblings.",
    accompanyingRelationship: "Relationship",
    accompanyingRelationshipAria: "Accompanying relationship",
    addAccompanyingFamily: "Add accompanying family member",
    koreaVisitCount: "Total visits to Korea in the last 5 years",
    latestVisitPurpose: "Purpose of most recent visit",
    visitPurposeExample: "e.g. tourism, business",
    arrivalDate: "Arrival date",
    departureDate: "Departure date",
    noKoreaVisitDetail: "No detailed Korea visit record is required when the count is zero.",
    travelIntro: "List every trip outside Korea during the last five years, including exact arrival and departure dates.",
    travelCountry: "Travel country",
    travelCountryPlaceholder: "Country",
    travelPurpose: "Travel purpose",
    travelPurposePlaceholder: "Purpose",
    removeTrip: "Remove trip",
    addTrip: "Add trip",
    attachmentsIntro: "Upload each required file here. Every completed upload is saved immediately and remains available after you refresh or return later.",
    passportCopy: "Passport copy",
    passportCopyHint: "Upload one clear passport copy as a PDF or image.",
    dancerProfile: "Personal dancer profile",
    dancerProfileHint: "Upload one dancer profile as a PDF or image.",
    idPhoto: "ID photo (35 × 45 mm)",
    idPhotoHint: "White background, no hat, front-facing, taken within the last six months, and different from the passport photo.",
    activityPhotos: "Major activity photos",
    activityPhotosHint: "Upload at least four images. You may add more, and photos previously posted on Instagram are accepted.",
    acceptedFileTypes: "JPG, PNG, WEBP, HEIC, or PDF · large files use resumable upload",
    acceptedImageTypes: "JPG, PNG, WEBP, or HEIC · large compatible photos are optimized automatically",
    chooseFile: "Choose file",
    replaceFile: "Replace",
    openFile: "Open",
    deleteFile: "Delete",
    uploadingFile: "Uploading…",
    activityPhotoProgress: (count: number) => `${count} uploaded · at least 4 required`,
    addActivityPhotos: "Choose multiple photos",
    activityPhotoNumber: (number: number) => `Photo ${number}`,
    sensitiveConsent: "I separately consent to deetz processing the following unique identification information.\nItems: passport numbers and home-country national identification number.\nPurpose: Korean visa document preparation and related administration.\nRetention: until the visa document preparation and related administration end.\nYou may refuse, but deetz cannot prepare documents that require these identifiers without your consent.",
    privacyPolicy: "Read the privacy policy",
    truthfulnessConfirmation: "I confirm that the information is complete and accurate to the best of my knowledge.",
    previous: "Previous",
    saveAndContinue: "Save & continue",
    submitInformation: "Submit information",
    securityReminder: "Do not send passport or national identification numbers by email or chat. If a save error appears, keep this tab open and retry before leaving.",
  },
  ko: {
    languageLabel: "언어",
    backToVisa: "비자 및 한국 체류",
    secureIntake: "안전한 서류 제출",
    title: "비자 서류 정보",
    intro: "한국 비자 서류 준비에 필요한 정보를 입력해 주세요. 작성 중인 내용은 백그라운드에서 자동 저장되며, 여권번호와 본국 국가식별번호는 암호화해서 보관합니다.",
    steps: ["기본 인적사항", "국적 및 여권", "비상 연락처", "학력", "혼인 및 가족", "최근 한국 방문", "해외 방문", "첨부자료 및 제출"],
    stepProgress: (current: number, total: number, title: string) => `${total}단계 중 ${current}단계 · ${title}`,
    saving: "저장 중…",
    saved: "저장됨",
    submitted: "제출 완료",
    reloadRequired: "새로고침 필요",
    saveFailed: "저장 실패",
    changesPending: "저장 대기 중",
    submitAfterSaving: "임시저장이 끝난 뒤 다시 제출해 주세요.",
    submitSuccess: "정보가 제출되었습니다. 추가 확인이 필요하면 담당자가 연락드리겠습니다.",
    validationError: "제출하기 전에 필수 항목과 확인 사항을 모두 입력해 주세요.",
    conflictError: "다른 탭에서 이 초안이 변경되었습니다. 페이지를 새로고침한 뒤 계속해 주세요.",
    acceptedError: "담당자가 접수 완료한 서류는 수정할 수 없습니다.",
    paidOnlyError: "본인이 결제 완료한 프로그램 건만 제출할 수 있습니다.",
    secureStorageError: "암호화 저장 기능을 일시적으로 사용할 수 없습니다. 잠시 후 다시 시도해 주세요.",
    draftSaveError: "임시저장하지 못했습니다. 입력한 내용은 현재 탭에 남아 있습니다.",
    attachmentIncomplete: "여권 사본 1개, 개인 댄서 프로필 1개, 증명사진 1개, 주요 활동 사진 최소 4장을 첨부한 뒤 제출해 주세요.",
    attachmentUploadFailed: "파일을 업로드하지 못했습니다. 다시 시도해 주세요.",
    attachmentDeleteFailed: "파일을 삭제하지 못했습니다. 다시 시도해 주세요.",
    attachmentSlotConflict: "다른 탭에서 같은 활동 사진 자리가 채워졌습니다. 페이지를 새로고침한 뒤 다시 시도해 주세요.",
    attachmentAcceptedError: "담당자가 검토 완료한 파일은 변경할 수 없습니다.",
    fullNameEnglish: "영문 성명",
    hanjaName: "한자 성명",
    hanjaHint: "DB상 선택 항목입니다. 일본·중국 등 한자를 사용하는 국가나 지역의 신청자는 반드시 입력해 주세요.",
    email: "이메일 주소",
    birthDate: "생년월일",
    mobilePhone: "휴대폰 번호",
    homeTelephone: "자택 전화번호",
    noHomeTelephone: "자택 전화번호가 없습니다.",
    homeCountryAddress: "본국 주소",
    currentResidenceDifferent: "현재 거주지 주소가 본국 주소와 다릅니다.",
    currentResidenceAddress: "현재 거주지 주소",
    koreaPlannedAddress: "한국 내 체류 예정 주소",
    nationalId: "본국 국가식별번호",
    nationalIdHint: "본국에서 발급한 주민등록번호 또는 국가식별번호를 입력해 주세요. 한국 주민등록번호는 입력하지 마세요.",
    japanNationalIdHint: "일본의 마이넘버는 이 페이지에서 수집하지 않습니다.",
    nationalIdNotApplicable: "발급받지 않았거나 해당 사항이 없습니다.",
    primaryNationality: "주 국적",
    dualNationalityQuestion: "복수 국적을 보유하고 있나요?",
    yes: "예",
    no: "아니요",
    otherNationalityCountries: "다른 국적 국가",
    countriesCommaHint: "여러 국가가 있으면 쉼표로 구분해 주세요.",
    primaryPassportType: "주 여권 종류",
    passportNumber: "주 여권 번호",
    passportIssuingCountry: "발급 국가",
    passportExpiryDate: "만료일",
    passportTypes: [
      { value: "ordinary", label: "일반" },
      { value: "diplomatic", label: "외교관" },
      { value: "official", label: "관용" },
      { value: "other", label: "기타" },
    ],
    hasOtherPassport: "다른 유효한 여권을 보유하고 있습니다.",
    otherPassportType: "여권 종류",
    otherPassportNumber: "여권 번호",
    removePassport: "여권 삭제",
    addPassport: "여권 추가",
    usedOtherName: "과거 한국 출입국 시 현재와 다른 성명을 사용한 적이 있습니다.",
    previousNamePlaceholder: "당시 사용한 영문 성명",
    previousNameAria: "과거 영문 성명",
    removeNameAria: "성명 삭제",
    addPreviousName: "과거 성명 추가",
    emergencyIntro: "한국 체류 중 연락 가능한 분을 입력해 주세요.",
    nameEnglish: "이름(영문)",
    phoneNumber: "전화번호",
    countryOfResidence: "거주 국가",
    countryExample: "예: 한국, 일본",
    relationship: "관계",
    relationshipExample: "예: 가족, 친구, 회사",
    highestEducation: "최종 학력",
    select: "선택해 주세요",
    educationLevels: [
      { value: "high_school", label: "고등학교 졸업" },
      { value: "bachelor", label: "대학교 졸업" },
      { value: "master", label: "석사" },
      { value: "doctorate", label: "박사" },
    ],
    schoolName: "학교 이름",
    city: "도시",
    region: "현·주·도",
    country: "국가",
    maritalStatus: "혼인 사항",
    maritalStatuses: [
      { value: "single", label: "미혼" },
      { value: "married", label: "기혼" },
      { value: "divorced", label: "이혼" },
    ],
    spouseName: "배우자 성명(영문)",
    spouseBirthDate: "배우자 생년월일",
    spouseNationality: "배우자 국적",
    spouseResidence: "배우자 거주지",
    spousePhone: "배우자 연락처",
    hasChildren: "자녀가 있습니다.",
    childrenCount: "자녀 수",
    hasFamilyInKorea: "현재 한국에 가족이 있습니다.",
    familyNamePlaceholder: "영문 성명",
    familyNameAria: "가족 성명",
    familyBirthDateAria: "가족 생년월일",
    familyNationality: "국적",
    familyNationalityAria: "가족 국적",
    familyRelationship: "관계",
    familyRelationshipAria: "가족 관계",
    remove: "삭제",
    addFamilyMember: "가족 추가",
    accompanyingFamilyQuestion: "이번 입국 시 동반 가족이 있습니다.",
    familyDefinition: "가족 범위는 배우자, 자녀, 부모, 형제입니다.",
    accompanyingRelationship: "관계",
    accompanyingRelationshipAria: "동반 가족 관계",
    addAccompanyingFamily: "동반 가족 추가",
    koreaVisitCount: "최근 5년간 한국 방문 횟수",
    latestVisitPurpose: "가장 최근 방문 목적",
    visitPurposeExample: "예: 여행, 비즈니스",
    arrivalDate: "입국일",
    departureDate: "출국일",
    noKoreaVisitDetail: "방문 횟수가 0회이면 상세 방문 기록을 입력하지 않아도 됩니다.",
    travelIntro: "최근 5년간 한국 외 국가를 방문한 기록을 모두 입력해 주세요. 입국일과 출국일은 날짜까지 필요합니다.",
    travelCountry: "방문 국가",
    travelCountryPlaceholder: "국가명",
    travelPurpose: "방문 목적",
    travelPurposePlaceholder: "목적",
    removeTrip: "방문 기록 삭제",
    addTrip: "방문 기록 추가",
    attachmentsIntro: "필요한 파일을 이 화면에서 첨부해 주세요. 업로드가 끝난 파일은 즉시 저장되어 새로고침하거나 나중에 다시 접속해도 유지됩니다.",
    passportCopy: "여권 사본",
    passportCopyHint: "내용이 선명하게 보이는 여권 사본 1개를 PDF 또는 이미지로 첨부해 주세요.",
    dancerProfile: "개인 댄서 프로필",
    dancerProfileHint: "개인 댄서 프로필 1개를 PDF 또는 이미지로 첨부해 주세요.",
    idPhoto: "증명사진 (35 × 45mm)",
    idPhotoHint: "흰색 바탕, 모자 미착용, 정면 촬영, 최근 6개월 이내 사진이어야 하며 여권사진과 달라야 합니다.",
    activityPhotos: "주요 활동 실적 사진",
    activityPhotosHint: "사진을 최소 4장 첨부해 주세요. 더 많이 첨부해도 되며 인스타그램에 올렸던 사진도 괜찮습니다.",
    acceptedFileTypes: "JPG, PNG, WEBP, HEIC 또는 PDF · 대용량 파일은 이어서 업로드",
    acceptedImageTypes: "JPG, PNG, WEBP 또는 HEIC · 대용량 호환 사진은 자동 최적화",
    chooseFile: "파일 선택",
    replaceFile: "교체",
    openFile: "열기",
    deleteFile: "삭제",
    uploadingFile: "업로드 중…",
    activityPhotoProgress: (count: number) => `${count}장 첨부 완료 · 최소 4장 필요`,
    addActivityPhotos: "여러 장 한 번에 선택",
    activityPhotoNumber: (number: number) => `사진 ${number}`,
    sensitiveConsent: "다음 고유식별정보 처리에 별도로 동의합니다.\n수집 항목: 여권번호와 본국 국가식별번호\n수집 목적: 한국 비자 서류 준비와 관련 행정 업무\n보유 기간: 비자 서류 준비와 관련 행정 업무가 끝날 때까지\n동의를 거부할 수 있으나, 거부하면 해당 식별정보가 필요한 비자 서류 준비를 진행할 수 없습니다.",
    privacyPolicy: "개인정보처리방침 보기",
    truthfulnessConfirmation: "입력한 내용이 제가 아는 범위에서 빠짐없이 정확하다는 것을 확인합니다.",
    previous: "이전",
    saveAndContinue: "저장 후 다음",
    submitInformation: "정보 제출",
    securityReminder: "여권번호나 본국 국가식별번호를 이메일 또는 메신저로 보내지 마세요. 저장 오류가 표시되면 이 탭을 닫지 말고 다시 시도해 주세요.",
  },
  ja: {
    languageLabel: "言語",
    backToVisa: "ビザ・韓国滞在",
    secureIntake: "安全な書類提出",
    title: "ビザ書類情報",
    intro: "韓国ビザ書類の準備に必要な情報を入力してください。入力中の内容はバックグラウンドで自動保存され、パスポート番号と本国の個人識別番号は暗号化して保管されます。",
    steps: ["基本情報", "国籍・パスポート", "緊急連絡先", "学歴", "婚姻・家族", "韓国への渡航歴", "海外渡航歴", "添付資料・提出"],
    stepProgress: (current: number, total: number, title: string) => `${total}ステップ中${current}ステップ · ${title}`,
    saving: "保存中…",
    saved: "保存済み",
    submitted: "提出済み",
    reloadRequired: "再読み込みが必要です",
    saveFailed: "保存できませんでした",
    changesPending: "保存待ち",
    submitAfterSaving: "一時保存が完了してから、もう一度提出してください。",
    submitSuccess: "情報を提出しました。追加確認が必要な場合は担当者からご連絡します。",
    validationError: "提出前に必須項目と確認事項をすべて入力してください。",
    conflictError: "別のタブでこの下書きが変更されました。ページを再読み込みしてから続けてください。",
    acceptedError: "担当者が受付を完了した書類は変更できません。",
    paidOnlyError: "ご本人が支払いを完了したプログラムのみ提出できます。",
    secureStorageError: "暗号化保存を一時的に利用できません。しばらくしてからもう一度お試しください。",
    draftSaveError: "一時保存できませんでした。入力した内容はこのタブに残っています。",
    attachmentIncomplete: "パスポートのコピー1点、個人ダンサープロフィール1点、証明写真1点、主な活動実績写真を最低4点添付してから提出してください。",
    attachmentUploadFailed: "ファイルをアップロードできませんでした。もう一度お試しください。",
    attachmentDeleteFailed: "ファイルを削除できませんでした。もう一度お試しください。",
    attachmentSlotConflict: "別のタブで同じ活動写真の枠が使用されました。ページを再読み込みしてからもう一度お試しください。",
    attachmentAcceptedError: "担当者が確認済みのファイルは変更できません。",
    fullNameEnglish: "氏名（英字）",
    hanjaName: "漢字氏名",
    hanjaHint: "システム上は任意項目ですが、日本・中国など漢字を使用する国・地域の申請者は必ず入力してください。",
    email: "メールアドレス",
    birthDate: "生年月日",
    mobilePhone: "携帯電話番号",
    homeTelephone: "自宅電話番号",
    noHomeTelephone: "自宅電話番号はありません。",
    homeCountryAddress: "本国の住所",
    currentResidenceDifferent: "現在の居住地が本国の住所と異なります。",
    currentResidenceAddress: "現在の居住地",
    koreaPlannedAddress: "韓国での滞在予定住所",
    nationalId: "本国の個人識別番号",
    nationalIdHint: "本国で発行された住民登録番号または個人識別番号を入力してください。韓国の住民登録番号は入力しないでください。",
    japanNationalIdHint: "日本のマイナンバーはこのページでは収集しません。",
    nationalIdNotApplicable: "発行されていない、または該当しません。",
    primaryNationality: "主な国籍",
    dualNationalityQuestion: "複数の国籍をお持ちですか？",
    yes: "はい",
    no: "いいえ",
    otherNationalityCountries: "その他の国籍",
    countriesCommaHint: "複数ある場合は、カンマで区切ってください。",
    primaryPassportType: "主なパスポートの種類",
    passportNumber: "主なパスポート番号",
    passportIssuingCountry: "発行国",
    passportExpiryDate: "有効期限",
    passportTypes: [
      { value: "ordinary", label: "一般" },
      { value: "diplomatic", label: "外交" },
      { value: "official", label: "公用" },
      { value: "other", label: "その他" },
    ],
    hasOtherPassport: "ほかに有効なパスポートを持っています。",
    otherPassportType: "パスポートの種類",
    otherPassportNumber: "パスポート番号",
    removePassport: "パスポートを削除",
    addPassport: "パスポートを追加",
    usedOtherName: "以前、現在と異なる氏名で韓国に入国または出国したことがあります。",
    previousNamePlaceholder: "当時使用した英字氏名",
    previousNameAria: "以前の英字氏名",
    removeNameAria: "氏名を削除",
    addPreviousName: "以前の氏名を追加",
    emergencyIntro: "韓国滞在中に連絡が取れる方を入力してください。",
    nameEnglish: "氏名（英字）",
    phoneNumber: "電話番号",
    countryOfResidence: "居住国",
    countryExample: "例：韓国、日本",
    relationship: "関係",
    relationshipExample: "例：家族、友人、会社",
    highestEducation: "最終学歴",
    select: "選択してください",
    educationLevels: [
      { value: "high_school", label: "高等学校卒業" },
      { value: "bachelor", label: "大学卒業" },
      { value: "master", label: "修士" },
      { value: "doctorate", label: "博士" },
    ],
    schoolName: "学校名",
    city: "市区町村",
    region: "都道府県・州",
    country: "国",
    maritalStatus: "婚姻状況",
    maritalStatuses: [
      { value: "single", label: "未婚" },
      { value: "married", label: "既婚" },
      { value: "divorced", label: "離婚" },
    ],
    spouseName: "配偶者の氏名（英字）",
    spouseBirthDate: "配偶者の生年月日",
    spouseNationality: "配偶者の国籍",
    spouseResidence: "配偶者の居住地",
    spousePhone: "配偶者の連絡先",
    hasChildren: "子どもがいます。",
    childrenCount: "子どもの人数",
    hasFamilyInKorea: "現在、韓国に家族がいます。",
    familyNamePlaceholder: "氏名（英字）",
    familyNameAria: "家族の氏名",
    familyBirthDateAria: "家族の生年月日",
    familyNationality: "国籍",
    familyNationalityAria: "家族の国籍",
    familyRelationship: "関係",
    familyRelationshipAria: "家族との関係",
    remove: "削除",
    addFamilyMember: "家族を追加",
    accompanyingFamilyQuestion: "今回の入国時に同行する家族がいます。",
    familyDefinition: "家族の範囲は、配偶者、子ども、両親、兄弟姉妹です。",
    accompanyingRelationship: "関係",
    accompanyingRelationshipAria: "同行家族との関係",
    addAccompanyingFamily: "同行家族を追加",
    koreaVisitCount: "過去5年間の韓国訪問回数",
    latestVisitPurpose: "直近の訪問目的",
    visitPurposeExample: "例：旅行、ビジネス",
    arrivalDate: "入国日",
    departureDate: "出国日",
    noKoreaVisitDetail: "訪問回数が0回の場合、詳細な訪問記録は不要です。",
    travelIntro: "過去5年間に韓国以外の国を訪問した記録をすべて入力してください。入国日と出国日は日付まで必要です。",
    travelCountry: "訪問国",
    travelCountryPlaceholder: "国名",
    travelPurpose: "訪問目的",
    travelPurposePlaceholder: "目的",
    removeTrip: "渡航記録を削除",
    addTrip: "渡航記録を追加",
    attachmentsIntro: "必要なファイルをこの画面で添付してください。アップロードが完了したファイルはすぐに保存され、再読み込みや後日の再アクセス後も保持されます。",
    passportCopy: "パスポートのコピー",
    passportCopyHint: "内容が鮮明に確認できるパスポートのコピー1点をPDFまたは画像で添付してください。",
    dancerProfile: "個人ダンサープロフィール",
    dancerProfileHint: "個人ダンサープロフィール1点をPDFまたは画像で添付してください。",
    idPhoto: "証明写真（35 × 45mm）",
    idPhotoHint: "白い背景、帽子なし、正面撮影、6か月以内に撮影した写真で、パスポート写真とは別の写真をご用意ください。",
    activityPhotos: "主な活動実績写真",
    activityPhotosHint: "画像を最低4点添付してください。4点を超えて追加でき、Instagramに投稿した写真も使用できます。",
    acceptedFileTypes: "JPG、PNG、WEBP、HEIC、PDF · 大容量ファイルは再開可能アップロードに対応",
    acceptedImageTypes: "JPG、PNG、WEBP、HEIC · 対応する大容量写真は自動最適化",
    chooseFile: "ファイルを選択",
    replaceFile: "差し替え",
    openFile: "開く",
    deleteFile: "削除",
    uploadingFile: "アップロード中…",
    activityPhotoProgress: (count: number) => `${count}点を添付済み · 最低4点必要`,
    addActivityPhotos: "複数の写真を選択",
    activityPhotoNumber: (number: number) => `写真 ${number}`,
    sensitiveConsent: "以下の個人識別情報の取扱いに別途同意します。\n収集項目：パスポート番号および本国の個人識別番号\n利用目的：韓国ビザ書類の準備および関連する行政手続き\n保有期間：ビザ書類の準備および関連する行政手続きが終了するまで\n同意を拒否できますが、その場合、当該識別情報が必要なビザ書類の準備はできません。",
    privacyPolicy: "プライバシーポリシーを見る",
    truthfulnessConfirmation: "入力した内容が、私の知る限り漏れなく正確であることを確認します。",
    previous: "前へ",
    saveAndContinue: "保存して次へ",
    submitInformation: "情報を提出",
    securityReminder: "パスポート番号や本国の個人識別番号をメールやチャットで送らないでください。保存エラーが表示された場合は、このタブを閉じずにもう一度お試しください。",
  },
} as const;

export function visaDocumentCopy(language: VisaDocumentLanguage) {
  return VISA_DOCUMENT_COPY[language];
}

