import {test} from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import {createTestDb,ids,mutate} from "./campaign-submissions-test-db.mjs";
test("operations RPC preserves approvals, permissions and fee reservations",async t=>{
 const pg=await createTestDb();t.after(()=>pg.close());
 await pg.exec(await fs.readFile(new URL("../db/migrations/20260908053312_campaign_operations.sql",import.meta.url),"utf8"));
 await pg.exec(await fs.readFile(new URL("../db/migrations/20260908055759_campaign_operations_consistency.sql",import.meta.url),"utf8"));
 await pg.exec("set role service_role");
 await mutate(pg,ids.admin,"configure",{version:0,enabled:true,board_id:ids.board,client_visible:false});
 await mutate(pg,ids.admin,"sync",{});
 const p=(await pg.query("select * from campaign_participants where dancer_id=$1",[ids.dancer])).rows[0];
 const call=(actor,action,data,project=ids.project)=>pg.query("select campaign_operations_mutate($1,$2,$3,$4)",[project,actor,action,JSON.stringify(data)]);
 const fields={engagement:"confirmed",planned_on:"2026-09-10",schedule_kind:"participation",owner_label:"매니저",upload_reported:false,next_action:"일정 확인",note:"확인 근거",accounts:[{handle:"diakang__",count:1,guide_amount:150000,agreed_amount:null}]};
 const terms={base_amount:0,bonus_amount:50000,threshold:10000,condition_state:"unmeasured"};
 const input={participant_id:p.id,participant_version:p.version,version:0,fields,fee:{version:0,status:"estimate",note:"1만 성과 시 5만원",terms}};
 await assert.rejects(call(ids.other,"participant",input),/CAMPAIGN_DENIED/);
 await assert.rejects(call(ids.member,"participant",input),/CAMPAIGN_DENIED/);
 await assert.rejects(call(ids.manager,"settings",{version:0,fields:{spend_target:7000000,spend_cap:8000000}}),/CAMPAIGN_DENIED/);
 await assert.rejects(call(ids.manager,"participant",{...input,fee:{...input.fee,terms:{...terms,bonus_amount:-1}}}),/CAMPAIGN_INVALID_INPUT/);
 await call(ids.manager,"participant",input);
 assert.equal(Number((await pg.query("select amount from campaign_budget_fees")).rows[0].amount),50000);
 await assert.rejects(call(ids.manager,"participant",input),/CAMPAIGN_STALE/);
 const current=(await pg.query("select version from campaign_participants where id=$1",[p.id])).rows[0];
 const submitted=await mutate(pg,ids.admin,"submit",{participant_id:p.id,url:"https://www.instagram.com/reel/testOps/",short_code:"testOps"});
 await mutate(pg,ids.admin,"review",{submission_id:submitted.id,version:1,status:"approved",checks:{public:true,account:true,guidelines:true}});
 await call(ids.manager,"participant",{...input,participant_version:current.version,version:1,fee:null,fields:{...fields,engagement:"cancelled"}});
 assert.equal((await pg.query("select active from campaign_participants where id=$1",[p.id])).rows[0].active,false);
 assert.equal(Number((await pg.query("select amount from campaign_budget_fees")).rows[0].amount),50000);
 assert.equal((await pg.query("select status from campaign_submissions where id=$1",[submitted.id])).rows[0].status,"approved");
 await call(ids.admin,"settings",{version:0,fields:{spend_target:7000000,spend_cap:8000000,notes:"원문 기록"}});
 await assert.rejects(call(ids.admin,"settings",{version:1,fields:{spend_target:9000000,spend_cap:8000000}}),/CAMPAIGN_INVALID_INPUT/);
 const privileges=(await pg.query("select has_table_privilege('anon','campaign_participant_operations','select') as anon,has_function_privilege('authenticated','campaign_operations_mutate(uuid,uuid,text,jsonb)','execute') as rpc")).rows[0];
 assert.equal(privileges.anon,false);assert.equal(privileges.rpc,false);
});
